language: cpp

sudo: required
dist: trusty

compiler:
  - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
  artifacts:
    s3_region: "ca-central-1"
    paths:
    - output-${TRAVIS_BUILD_NUMBER}.zip

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
 
before_script:
  - mkdir build && cd build
  - cmake ..

after_success:
    - zip output-${TRAVIS_BUILD_NUMBER} ./test

branches:
  only:
   - master
 
before_script: ls
 
script:
  - make -f factorial.mk && ./factorial